name: ForgeModBlocker
version: 1.3.1

author: Mas281
authors: [Mas281, Okx]

description: Control which mods your players can use
website: https://www.spigotmc.org/resources/forgemodblocker.45220/

main: me.jaden.forgemodblocker.ModBlockerBungeePlugin

softdepend: [PlaceholderAPI]

commands:
  fmb:
    aliases: [forgemodblocker, modblocker]
  mods:
    aliases: [modlist]

permissions:
  fmb.*:
    default: false
    children:
      fmb.bypass: true
      fmb.update_notification: true
      fmb.main_command: true
      fmb.reload_command: true
      fmb.mods_command: true
  fmb.bypass:
    default: false