name: ForgeModBlocker
version: 1.2.3
author: Mas281

main: me.itsmas.forgemodblocker.ForgeModBlocker

softdepend: [PlaceholderAPI]

permissions:
  fmb.*:
    default: false
  fmb.bypass:
    default: false