name: ForgeModBlocker
version: 1.0.0

author: Iowa
authors: [Mas281, Okx]

description: Control which mods your players can use
website: https://www.spigotmc.org/resources/forgemodblocker-for-bungee.75970/

main: me.jaden.forgemodblocker.ModBlockerBungeePlugin

commands:
  fmb:
    aliases: [forgemodblocker, modblocker]
  mods:
    aliases: [modlist]

permissions:
  fmb.*:
    default: false
    children:
      fmb.bypass: true
      fmb.update_notification: true
      fmb.main_command: true
      fmb.reload_command: true
      fmb.mods_command: true
  fmb.bypass:
    default: false